name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  dotnet_sdk_version: '5.0.x'
  postgis_version: 3
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      is_release: ${{ steps.analyze_tag.outputs.is_release }}
      is_prerelease: ${{ steps.analyze_tag.outputs.is_prerelease }}

    steps:
      - id: analyze_tag
        name: Analyze tag
        shell: bash
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "Release tag detected"
              echo "::set-output name=is_release::true"
              if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+.*- ]]; then
                  echo "Prerelease tag detected"
                  echo "::set-output name=is_prerelease::true"
              fi
          fi

  release:
    needs: build

    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'roji/npgsql' && needs.build.outputs.is_release == 'true'

    steps:
      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
# TODO: Chop off leading v, and remove -* for previews (point to the 6.0.0 milestone from v6.0.0-preview1)          
#          body: The list of changes is available [here](https://github.com/npgsql/npgsql/issues?q=is%3Aissue+milestone%3A${{ env.tag_name }}).
          prerelease: ${{ needs.build.outputs.is_prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}


#      - name: Publish to nuget.org
#        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_ORG_API_KEY }} #--source https://www.myget.org/F/npgsql/api/v3/index.json
#        working-directory: nupkgs
#        shell: bash
