name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  dotnet_sdk_version: '5.0.x'
  postgis_version: 3
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      release: ${{ steps.check_release.outputs.release }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-2019 ]
        pg_major: [ 13, 12, 11, 10 ]

    steps:
      - id: check_release
        name: Check whether to release
        shell: bash
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "::set-output name=release::true"
          fi

  publish:
    needs: build

    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'roji/npgsql' && needs.build.outputs.release == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
